# fly.toml app configuration file generated for wheres-waldo-mern-api on 2024-06-23T20:22:38+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'wheres-waldo-mern-api'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
